apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    app: postgres
    component: database
type: Opaque
stringData:
  username: "postgres"
  password: "jjksdj112n_12mD!#"

# Made with Bob
