apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    app: postgres
    component: database
type: Opaque
stringData:
  username: "postgres"
  password: "CHANGE_ME_IN_PRODUCTION"

# Made with Bob
