apiVersion: batch/v1
kind: Job
metadata:
  name: database-seed
  labels:
    app: database
    component: seed
spec:
  ttlSecondsAfterFinished: 300
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: database
        component: seed
    spec:
      restartPolicy: Never
      containers:
      - name: seed
        image: ecommerce-backend:latest
        command: ["node", "/app/src/scripts/seed.js"]
        env:
        - name: NODE_ENV
          value: "production"
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: database.host
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: database.port
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: database.name
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: database.user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: database.password
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: jwt.secret

# Made with Bob