apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: backend-success-rate
spec:
  args:
  - name: service-name
  - name: prometheus-url
    value: http://prometheus.monitoring.svc.cluster.local:9090
  
  metrics:
  # Success rate metric
  - name: success-rate
    interval: 30s
    successCondition: result[0] >= 0.95
    failureLimit: 3
    provider:
      prometheus:
        address: "{{args.prometheus-url}}"
        query: |
          sum(rate(
            http_requests_total{
              service="{{args.service-name}}",
              status=~"2.."
            }[2m]
          )) 
          / 
          sum(rate(
            http_requests_total{
              service="{{args.service-name}}"
            }[2m]
          ))
  
  # Error rate metric
  - name: error-rate
    interval: 30s
    successCondition: result[0] <= 0.05
    failureLimit: 3
    provider:
      prometheus:
        address: "{{args.prometheus-url}}"
        query: |
          sum(rate(
            http_requests_total{
              service="{{args.service-name}}",
              status=~"5.."
            }[2m]
          )) 
          / 
          sum(rate(
            http_requests_total{
              service="{{args.service-name}}"
            }[2m]
          ))
  
  # Response time metric (p95)
  - name: response-time-p95
    interval: 30s
    successCondition: result[0] <= 500
    failureLimit: 3
    provider:
      prometheus:
        address: "{{args.prometheus-url}}"
        query: |
          histogram_quantile(0.95,
            sum(rate(
              http_request_duration_milliseconds_bucket{
                service="{{args.service-name}}"
              }[2m]
            )) by (le)
          )

# Made with Bob