apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: backend
  labels:
    app: backend
    app.kubernetes.io/name: backend
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: ecommerce
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: backend
      app.kubernetes.io/name: backend
      app.kubernetes.io/component: api
      app.kubernetes.io/part-of: ecommerce
  
  template:
    metadata:
      labels:
        app: backend
        app.kubernetes.io/name: backend
        app.kubernetes.io/component: api
        app.kubernetes.io/part-of: ecommerce
        component: api
    spec:
      containers:
      - name: backend
        image: ecommerce-backend
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: NODE_ENV
          value: production
        - name: PORT
          value: "3000"
        - name: DATABASE_HOST
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: database.host
        - name: DATABASE_PORT
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: database.port
        - name: DATABASE_NAME
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: database.name
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: database.user
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: database.password
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: jwt.secret
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health/live
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
  
  # Canary Strategy
  strategy:
    canary:
      # Service references for traffic routing
      canaryService: backend-canary
      stableService: backend-stable
      
      # Number of pods to run for canary
      canaryReplicas: 1
      
      # Steps for progressive rollout
      steps:
      # Step 1: Deploy canary with 20% traffic
      - setWeight: 20
      - pause: {duration: 2m}
      
      # Step 2: Increase to 40% traffic
      - setWeight: 40
      - pause: {duration: 2m}
      
      # Step 3: Increase to 60% traffic
      - setWeight: 60
      - pause: {duration: 2m}
      
      # Step 4: Increase to 80% traffic
      - setWeight: 80
      - pause: {duration: 2m}
      
      # Step 5: Full rollout (100%)
      - setWeight: 100
      
      # Traffic routing (requires service mesh or ingress controller)
      trafficRouting:
        nginx:
          stableIngress: ecommerce-ingress
          annotationPrefix: nginx.ingress.kubernetes.io
      
      # Analysis for automated promotion/rollback
      # Disabled until Prometheus is installed
      # analysis:
      #   templates:
      #   - templateName: backend-success-rate
      #   startingStep: 1
      #   args:
      #   - name: service-name
      #     value: backend

# Made with Bob