apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  labels:
    app: backend
    component: api
type: Opaque
stringData:
  # Database credentials
  database.user: "ecommerce_user"
  database.password: "ecommerce_password"
  
  # JWT secret for authentication
  jwt.secret: "adfhjdf@1!@hjsklasd"

# Made with Bob
