apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  labels:
    app: backend
    component: api
type: Opaque
stringData:
  jwt.secret: "CHANGE_ME_IN_PRODUCTION_USE_STRONG_SECRET"

# Made with Bob
