apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  labels:
    app: backend
    component: api
type: Opaque
stringData:
  # Database credentials (must match postgres-secret)
  database.user: "postgres"
  database.password: "jjksdj112n_12mD!#"
  
  # JWT secret for authentication
  jwt.secret: "adfhjdf@1!@hjsklasd"

# Made with Bob
