# Canary Service - Routes traffic to canary pods
apiVersion: v1
kind: Service
metadata:
  name: backend-canary
  labels:
    app: backend
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: backend

---
# Stable Service - Routes traffic to stable pods
apiVersion: v1
kind: Service
metadata:
  name: backend-stable
  labels:
    app: backend
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: backend

# Made with Bob