# Canary Service - Routes traffic to canary pods
apiVersion: v1
kind: Service
metadata:
  name: backend-canary
  labels:
    app: backend
    app.kubernetes.io/name: backend
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: ecommerce
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: backend
    app.kubernetes.io/name: backend
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: ecommerce
    # This label is automatically added by Argo Rollouts to canary pods
    rollouts-pod-template-hash: canary

---
# Stable Service - Routes traffic to stable pods
apiVersion: v1
kind: Service
metadata:
  name: backend-stable
  labels:
    app: backend
    app.kubernetes.io/name: backend
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: ecommerce
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: backend
    app.kubernetes.io/name: backend
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: ecommerce
    # This label is automatically added by Argo Rollouts to stable pods
    rollouts-pod-template-hash: stable

# Made with Bob