apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ecommerce-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/emil-ep/argo-app.git
    targetRevision: master
    path: gitops/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: ecommerce-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
    - group: argoproj.io
      kind: Rollout
      jsonPointers:
        - /status
        - /spec/template/metadata/annotations/kubectl.kubernetes.io~1restartedAt
        - /spec/strategy/canary/canaryReplicas
    - group: batch
      kind: Job
      jsonPointers:
        - /spec/template/metadata/labels/batch.kubernetes.io~1controller-uid
        - /spec/template/metadata/labels/batch.kubernetes.io~1job-name
        - /spec/template/metadata/labels/controller-uid
        - /spec/template/metadata/labels/job-name

# Made with Bob
